---

# ######################
# #### Validate vars ###
# ######################

- include_role:
    name: microk8s

# - include_role:
#     name: k3s

# - include_role:
#     name: dt-operator

# - include_role:
#     name: app-unguard

# - include_role:
#     name: app-easytrade

# - include_role:
#     name: app-easytravel

# - include_role:
#   name: app-hipstershop

# Include and template use case specific values before installing Dashboard
# - set_fact:
#     include_dashboard_value_file: "{{ role_path }}/templates/my-use-case-dashboard.yml.j2"

# - include_role:
#     name: dashboard
#     tasks_from: template-values-file

# - include_role:
#     name: dashboard
