---

# ######################
# #### Validate vars ###
# ######################

- name: Setup
  shell: >
    sudo useradd -m -s /bin/bash user-xxx \
    && echo "user-xxx:secretpwd" | sudo chpasswd \
    && sudo sh -c 'echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/60-cloudimg-settings.conf' \
    && sudo sshd -t && sudo systemctl restart sshd

- include_role:
    name: dt-oneagent-classic
    
# - include_role:
#     name: k3s

# - include_role:
#     name: dt-operator

# - include_role:
#     name: app-unguard

# - include_role:
#     name: app-easytrade

# - include_role:
#     name: app-easytravel

# - include_role:
#   name: app-hipstershop

# Include and template use case specific values before installing Dashboard
# - set_fact:
#     include_dashboard_value_file: "{{ role_path }}/templates/my-use-case-dashboard.yml.j2"

# - include_role:
#     name: dashboard
#     tasks_from: template-values-file

# - include_role:
#     name: dashboard
