---

# ######################
# #### Validate vars ###
# ######################

# #Generate OAuth Token
# - block:
#     - name: Request a DT OAuth access token
#       ansible.builtin.uri:
#         url: "{{ extra_vars.dt_oauth_sso_endpoint }}"
#         method: POST
#         status_code: 200
#         headers:
#           Content-Type: "application/x-www-form-urlencoded"
#         body_format: form-urlencoded
#         body:
#           grant_type: "client_credentials"
#           client_id: "{{ extra_vars.dt_oauth_client_id }}"
#           client_secret: "{{ extra_vars.dt_oauth_client_secret }}"
#           scope: "document:documents:read document:documents:write document:direct-shares:read document:direct-shares:write"
#           resource: "{{ extra_vars.dt_oauth_account_urn }}"
#       register: auth_response_raw
#     - set_fact:
#         dt_oauth_access_token: "{{ auth_response_raw.json.access_token }}"

# - include_role:
#     name: monaco-v2

# - include_role:
#     name: monaco-v2
#     tasks_from: apply-monaco
#   vars:
#     monaco_projects_root: "{{role_path_abs}}/files/monaco"  # monaco projects root folder path
#     monaco_project: "deploy" # selection of projects or all projects under the root path if set empty
#     monaco_manifest_path: "{{role_path_abs}}/files/monaco/manifest.yaml"
#     monaco_environment:
#       #SLACK_TOKEN: "{{ extra_vars.slack_token }}"
#       JIRA_CONNECTION_TOKEN: "{{ extra_vars.jira_connection_token }}"
#       DT_API_TOKEN: "{{ monaco_cleanup_api_token }}"
#       DT_PLATFORM_TENANT_URL: "{{ extra_vars.dt_environment_url_gen3 }}"
#       DT_OAUTH_CLIENT_ID: "{{ extra_vars.dt_oauth_client_id }}"
#       DT_OAUTH_CLIENT_SECRET: "{{ extra_vars.dt_oauth_client_secret }}"
#       DT_OAUTH_SSO_ENDPOINT: "{{ extra_vars.dt_oauth_sso_endpoint }}"
#       INGRESS_DOMAIN: "{{ ingress_domain }}"

# - include_role:
#     name: microk8s

- include_role:
    name: k3s

- include_role:
    name: dt-operator

- include_role:
    name: app-unguard

# - include_role:
#     name: app-easytrade

# - include_role:
#     name: app-easytravel

# - include_role:
#   name: app-hipstershop

# Include and template use case specific values before installing Dashboard
# - set_fact:
#     include_dashboard_value_file: "{{ role_path }}/templates/my-use-case-dashboard.yml.j2"

# - include_role:
#     name: dashboard
#     tasks_from: template-values-file

# - include_role:
#     name: dashboard
