manifestVersion: 1.0
projects:
  - name: outbound-connection
  - name: builtinappsec.runtime-vulnerability-detection
  - name: appdynatrace.jiraconnection
  - name: workflow
environmentGroups:
- name: development
  environments:
      - name: dev
        url:
          type: environment
          value: DT_PLATFORM_TENANT_URL
        auth:
          token:
            type: environment
            name: DT_API_TOKEN
          oAuth:
            clientId:
              name: DT_OAUTH_CLIENT_ID
            clientSecret:
              name: DT_OAUTH_CLIENT_SECRET
            tokenEndpoint:
              type: environment
              value: DT_OAUTH_SSO_ENDPOINT
